# Generated by Django 6.0.2 on 2026-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WomenSafetyRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('personal', 'Personal Safety'), ('workplace', 'Workplace Rights'), ('property', 'Property Rights'), ('family', 'Family Law'), ('legal', 'Legal Protection'), ('health', 'Health & Medical Rights'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('rights_provided', models.TextField(help_text='What rights does a woman have?')),
                ('legal_reference', models.CharField(help_text='Law or Act reference (e.g., IPC 376, Dowry Prohibition Act)', max_length=200)),
                ('how_to_get_help', models.TextField(help_text='Step-by-step guide to access or exercise this right')),
                ('prevention_tips', models.TextField(blank=True, help_text='Prevention or protective tips')),
                ('resources', models.TextField(blank=True, help_text='Helpful organizations, helplines, websites')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Women's Safety Right",
                'verbose_name_plural': "Women's Safety Rights",
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['category'], name='women_safet_categor_1d8102_idx'), models.Index(fields=['title'], name='women_safet_title_bf85d7_idx')],
            },
        ),
    ]
