# Generated by Django 6.0.2 on 2026-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='womensafetyright',
            name='penalties',
            field=models.TextField(blank=True, help_text='Penalties for violating this law'),
        ),
    ]
