# Generated by Django 6.0.2 on 2026-03-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.FloatField(help_text='GPS latitude')),
                ('longitude', models.FloatField(help_text='GPS longitude')),
                ('jurisdiction', models.TextField(blank=True, help_text='Area of jurisdiction')),
                ('opening_hours', models.CharField(default='24/7', max_length=200)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to='regions.state')),
            ],
            options={
                'verbose_name': 'Police Station',
                'verbose_name_plural': 'Police Stations',
                'ordering': ['state', 'district', 'name'],
                'indexes': [models.Index(fields=['state', 'city'], name='police_stat_state_i_4b34bc_idx'), models.Index(fields=['district'], name='police_stat_distric_074bcf_idx')],
            },
        ),
    ]
