# Generated by Django 6.0.2 on 2026-04-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='office_type',
            field=models.CharField(choices=[('police', 'General Police Station'), ('traffic', 'Traffic Police Station'), ('registration', 'Registration & Sub-Registrar Office')], default='police', max_length=20),
        ),
    ]
