# Generated by Django 6.0.2 on 2026-03-23 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('driving_license', 'Driving License'), ('pan_card', 'PAN Card'), ('voter_id', 'Voter ID'), ('vehicle_registration', 'Vehicle Registration')], max_length=200, unique=True)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('required_fields', models.TextField(help_text='JSON or comma-separated list of required fields')),
                ('fees', models.CharField(max_length=200)),
                ('processing_days', models.IntegerField(help_text='Average processing time in days')),
            ],
            options={
                'verbose_name': 'Application Service',
                'verbose_name_plural': 'Application Services',
            },
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='submitted', max_length=20)),
                ('form_data', models.JSONField(help_text='Application form data')),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Application',
                'verbose_name_plural': 'User Applications',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', '-submitted_at'], name='application_user_id_8fabfe_idx'), models.Index(fields=['status'], name='application_status_400384_idx')],
            },
        ),
    ]
