# Generated by Django 6.0.2 on 2026-03-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationservice',
            name='name',
            field=models.CharField(choices=[('aadhaar_card', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('income_certificate', 'Income Certificate'), ('caste_certificate', 'Caste Certificate'), ('birth_death_certificate', 'Birth/Death Certificate'), ('ration_card', 'Ration Card')], max_length=200, unique=True),
        ),
    ]
