# Generated by Django 6.0.2 on 2026-03-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicationservice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationservice',
            name='application_format_url',
            field=models.URLField(blank=True, help_text='Link to official PDF or application format'),
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='official_website',
            field=models.URLField(blank=True, help_text='Verified government portal URL'),
        ),
    ]
