# Generated by Django 6.0.2 on 2026-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationservice_application_format_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationservice',
            name='direct_apply',
            field=models.BooleanField(default=True, help_text='If True, user can apply directly on this site. If False, we point to offline/govt centers.'),
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='offline_instructions',
            field=models.TextField(blank=True, help_text='Instructions for MeeSeva / CSC / Office applications if direct_apply is False.'),
        ),
    ]
