# Generated by Django 6.0.2 on 2026-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationservice_direct_apply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationservice',
            name='requires_physical_verification',
            field=models.BooleanField(default=False, help_text='Set to True if the applicant must physically visit a center for biometrics or document verification.'),
        ),
    ]
