# Generated by Django 6.0.2 on 2026-02-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentalRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('legal_explanation', models.TextField()),
                ('simple_explanation', models.TextField()),
                ('violation_example', models.TextField()),
                ('what_to_do', models.TextField()),
                ('where_to_complain', models.TextField()),
                ('court_remedy', models.TextField()),
                ('case_references', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rights.rightcategory')),
            ],
        ),
    ]
