# Generated by Django 6.0.2 on 2026-03-23 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundamentalright',
            options={'ordering': ['article_number'], 'verbose_name': 'Fundamental Right', 'verbose_name_plural': 'Fundamental Rights'},
        ),
        migrations.AlterModelOptions(
            name='rightcategory',
            options={'ordering': ['name'], 'verbose_name': 'Right Category', 'verbose_name_plural': 'Right Categories'},
        ),
        migrations.AddField(
            model_name='fundamentalright',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundamentalright',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rightcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rightcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='article_number',
            field=models.CharField(db_index=True, help_text='Example: "14", "19(1)(a)"', max_length=20),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='case_references',
            field=models.TextField(blank=True, help_text='Important case references and judgments'),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rights', to='rights.rightcategory'),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='court_remedy',
            field=models.TextField(help_text='What remedies are available through courts'),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=300),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='legal_explanation',
            field=models.TextField(help_text='Official legal explanation of the right'),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='simple_explanation',
            field=models.TextField(help_text='Simple, non-technical explanation for common people'),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='violation_example',
            field=models.TextField(help_text='Example of what happens when this right is violated'),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='what_to_do',
            field=models.TextField(help_text='What steps should a person take if their rights are violated?'),
        ),
        migrations.AlterField(
            model_name='fundamentalright',
            name='where_to_complain',
            field=models.TextField(help_text='Where to file a complaint or petition'),
        ),
        migrations.AlterField(
            model_name='rightcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='fundamentalright',
            index=models.Index(fields=['article_number'], name='rights_fund_article_7f837e_idx'),
        ),
        migrations.AddIndex(
            model_name='fundamentalright',
            index=models.Index(fields=['title'], name='rights_fund_title_1835e8_idx'),
        ),
        migrations.AddIndex(
            model_name='fundamentalright',
            index=models.Index(fields=['category'], name='rights_fund_categor_39611b_idx'),
        ),
    ]
