# Generated by Django 6.0.2 on 2026-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0002_alter_fundamentalright_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('short_name', models.CharField(help_text='Common name (e.g., PoSH, PF Act)', max_length=100)),
                ('applies_to', models.TextField(help_text='Who does this act apply to? (e.g. Any office with >10 employees)')),
                ('description', models.TextField(help_text='General description of the law')),
                ('employee_rights', models.TextField(help_text='What rights the employee has under this law')),
                ('employer_duties', models.TextField(help_text='Mandatory obligations for the employer')),
                ('violation_consequences', models.TextField(help_text='What happens if the employer breaks this law?')),
                ('where_to_complain', models.TextField(help_text='Where mapping or exact department to file complaint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workplace Law',
                'verbose_name_plural': 'Workplace Laws',
                'ordering': ['title'],
            },
        ),
    ]
