# Generated by Django 6.0.2 on 2026-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('document_type', models.CharField(choices=[('identity', 'Identity Documents'), ('travel', 'Travel Documents'), ('registry', 'Registry & Licensing'), ('certificate', 'Certificates'), ('permit', 'Permits & Licenses'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('purpose', models.TextField(help_text='Why is this document needed?')),
                ('eligibility', models.TextField(help_text='Who is eligible to apply?')),
                ('required_documents', models.TextField(help_text='List of required documents/files')),
                ('step_by_step_guide', models.TextField(help_text='Step-by-step application process')),
                ('fees', models.CharField(blank=True, help_text='Application fees', max_length=200)),
                ('processing_time', models.CharField(blank=True, help_text='Expected processing time', max_length=200)),
                ('official_website', models.URLField(help_text='Official government website link')),
                ('alternative_guides', models.URLField(blank=True, help_text='Other helpful resources')),
                ('guide_pdf', models.FileField(blank=True, help_text='PDF guide for this document', upload_to='documents/guides/')),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Document',
                'verbose_name_plural': 'Government Documents',
                'ordering': ['document_type', 'name'],
                'indexes': [models.Index(fields=['document_type'], name='documents_g_documen_efd673_idx'), models.Index(fields=['name'], name='documents_g_name_7e964a_idx')],
            },
        ),
    ]
