# Generated by Django 6.0.2 on 2026-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentdocument',
            name='common_mistakes',
            field=models.TextField(blank=True, help_text='Common reasons for application rejection'),
        ),
        migrations.AddField(
            model_name='governmentdocument',
            name='direct_apply_available',
            field=models.BooleanField(default=False, help_text='Can a citizen apply for this directly online?'),
        ),
        migrations.AddField(
            model_name='governmentdocument',
            name='offline_centers',
            field=models.TextField(blank=True, help_text='Where to go for offline application (e.g. MeeSeva, CSC, District Office)'),
        ),
    ]
