# Generated by Django 6.0.2 on 2026-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_governmentdocument_common_mistakes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentdocument',
            name='document_checklist',
            field=models.TextField(blank=True, help_text="Line-separated list of items needed (e.g., '2 Passport Photos', 'Aadhaar Card copy')"),
        ),
    ]
