# Generated by Django 6.0.2 on 2026-03-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'State/UT',
                'verbose_name_plural': 'States/UTs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionalLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('act_name', models.CharField(help_text='Name of the Act or Law (e.g., Kashmir Administrative Act)', max_length=200)),
                ('description', models.TextField()),
                ('key_provisions', models.TextField(help_text='Important provisions and details of the law')),
                ('who_it_applies_to', models.TextField(help_text='Who does this law apply to?')),
                ('penalties_punishments', models.TextField(blank=True, help_text='What are the penalties for violation?')),
                ('how_to_comply', models.TextField(help_text='How to comply with this law')),
                ('official_link', models.URLField(blank=True, help_text='Link to official government website for this law')),
                ('effective_date', models.DateField(blank=True, help_text='When did this law come into effect?', null=True)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='regions.state')),
            ],
            options={
                'verbose_name': 'Regional Law',
                'verbose_name_plural': 'Regional Laws',
                'ordering': ['state', 'title'],
                'indexes': [models.Index(fields=['state'], name='regions_reg_state_i_234583_idx'), models.Index(fields=['title'], name='regions_reg_title_cde415_idx')],
            },
        ),
    ]
