# Generated by Django 6.0.2 on 2026-02-25 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='violated_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rights.fundamentalright'),
        ),
    ]
