# Generated by Django 6.0.2 on 2026-03-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_violated_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='tracking_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
