# Generated by Django 6.0.2 on 2026-04-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_options_complaint_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='evidence',
            field=models.FileField(blank=True, help_text='Upload supporting documents, photos, or recordings (Max 10MB)', null=True, upload_to='complaints/evidence/%Y/%m/%d/'),
        ),
    ]
