# Generated by Django 6.0.2 on 2026-03-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('emergency', 'Emergency Services'), ('women_safety', 'Women Safety'), ('child_safety', 'Child Safety'), ('mental_health', 'Mental Health'), ('legal_aid', 'Legal Aid'), ('labor', 'Labor Rights'), ('environment', 'Environment'), ('other', 'Other')], db_index=True, max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('phone_alternative', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('scope', models.CharField(help_text='National / State / City', max_length=100)),
                ('availability', models.CharField(default='24/7', help_text='Availability hours', max_length=200)),
                ('languages', models.CharField(blank=True, help_text='Languages supported (comma-separated)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helplines', to='regions.state')),
            ],
            options={
                'verbose_name': 'Helpline',
                'verbose_name_plural': 'Helplines',
                'ordering': ['category', 'scope'],
                'indexes': [models.Index(fields=['category'], name='helplines_h_categor_1ef03a_idx'), models.Index(fields=['state'], name='helplines_h_state_i_611456_idx')],
            },
        ),
    ]
