# Generated by Django 6.0.2 on 2026-03-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rights', '0002_alter_fundamentalright_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationConsequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immediate_effects', models.TextField(help_text='What are the immediate effects of violation?')),
                ('long_term_effects', models.TextField(help_text='Long-term consequences')),
                ('legal_remedies', models.TextField(help_text='What legal remedies are available?')),
                ('compensation_options', models.TextField(blank=True, help_text='What compensation can be claimed?')),
                ('prevention_measures', models.TextField(help_text='How can such violations be prevented?')),
                ('case_examples', models.TextField(blank=True, help_text='Real case examples')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fundamental_right', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violation_consequence', to='rights.fundamentalright')),
            ],
            options={
                'verbose_name': 'Violation Consequence',
                'verbose_name_plural': 'Violation Consequences',
            },
        ),
    ]
