# Generated by Django 6.0.2 on 2026-04-08 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0003_workplacelaw'),
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('traffic', 'Traffic Violations'), ('police', 'Police Issues'), ('workplace', 'Workplace Issues'), ('domestic', 'Domestic & Family'), ('discrimination', 'Discrimination'), ('medical', 'Medical & Healthcare'), ('consumer', 'Consumer Rights'), ('other', 'Other')], default='other', max_length=20)),
                ('is_legal', models.BooleanField(default=False, help_text='Is this action legal? (Checked = YES, Unchecked = NO)')),
                ('simple_explanation', models.TextField(help_text="Very simple English explanation of why this is/isn't legal")),
                ('step_by_step_guide', models.TextField(help_text='Numbered list: What should the user do now?')),
                ('where_to_complain', models.TextField(help_text='Exact authority, platform, or office to file a complaint')),
                ('legal_remedies', models.TextField(help_text='What legal actions can be taken?')),
                ('compensation_details', models.TextField(blank=True, help_text='Is there any money or relief the user can claim?')),
                ('prevention_tips', models.TextField(blank=True, help_text='How to avoid this situation in the future')),
                ('real_life_example', models.TextField(help_text='A story-based example of this situation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_right', models.ForeignKey(blank=True, help_text='Which Fundamental Right covers this situation?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situations', to='rights.fundamentalright')),
            ],
            options={
                'verbose_name': 'Violation Situation',
                'verbose_name_plural': 'Violation Situations',
                'ordering': ['-created_at'],
            },
        ),
    ]
