# Generated by Django 6.0.2 on 2026-04-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_violationsituation'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationsituation',
            name='landmark_judgment',
            field=models.TextField(blank=True, help_text='Supreme Court or High Court landmark judgments related to this situation'),
        ),
    ]
